spring.application.name=tienda
server.port=8081

#Definir formato fecha
logging.pattern.dateformat=hh:mm

#Eliminar mensajes de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en producción (true)
spring.thymeleaf.cache=false